version: '1'

services:
	postgres:
		image: postgres:9.6
		container_name: postgres
		environment:
			POSTGRES_USER: portfolio
			POSTGRES_PASSWORD: J5brHrAXFLQSif0K
			POSTGRES_DB: portfolio

	portfolio:
		build: .
		image: chamaconekt/portfolio
		links:
		- postgres
		container_name: portfolio
		depends_on:
			- postgres
		environment:

	nginx:
		image: nginx:1.11.11-alpine
		links:
			- portfolio
		container_name: nginx
		command: nginx -g 'daemon off;' -c /etc/portfolio-nginx/nginx.conf
		depends_on:
			- portfolio
		ports:
			- 80:80
		volumes_from:
			- portfolio

volumes:
	portfolio-static-files:
		driver:local